apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    node.number: "3"
    node.current: "_NODE_ID_"
  creationTimestamp: null
  labels:
    name: node-_NODE_ID_
  name: node-_NODE_ID_
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consortiumchain
        name: node-_NODE_ID_
        service.rpc: node-_NODE_ID_
    spec:
      containers:
      - image: asia.gcr.io/consortiumchain/quorum
        name: node-_NODE_ID_
        command: ["/bin/bash"]
        args:
        - "-cx"
        - |-
          _NODE_SCRIPT_
        ports:
        - containerPort: 8545
        - containerPort: 23000
        - containerPort: 9000
        - containerPort: 30303
        resources: {}
        volumeMounts:
        - mountPath: /qdata
          name: node-_NODE_ID_
      restartPolicy: Always
      volumes:
      - name: node-_NODE_ID_
        persistentVolumeClaim:
          claimName: node-_NODE_ID_
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    name: node-_NODE_ID_
  name: node-_NODE_ID_
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app: consortiumchain
    version: '1'
  creationTimestamp: null
  labels:
    name: node-_NODE_ID_
  name: node-_NODE_ID_
spec:
  type: LoadBalancer
  clusterIP: "_NODE_IP_"
  ports:
  - name: rpc
    port: 8545
    targetPort: 8545
  - name: raft
    port: 23000
    targetPort: 23000
  - name: constellation
    port: 9000
    targetPort: 9000
  - name: tx
    port: 30303
    targetPort: 30303
  selector:
    service.rpc: node-_NODE_ID_
status:
  loadBalancer: {}
---
