apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    node.number: "3"
    node.current: "_NODE_ID_"
  creationTimestamp: null
  labels:
    node.name: node-_NODE_ID_
  name: node-_NODE_ID_
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quorum-consortium
        node.name: node-_NODE_ID_
        service: node-_NODE_ID_
    spec:
      containers:
      - image: quorum
        imagePullPolicy: Never
        name: node-_NODE_ID_
        command: ["/bin/bash"]
        args:
        - "-cx"
        - |-
          _NODE_SCRIPT_
        ports:
        - containerPort: 8545
        - containerPort: 23000
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /qdata
          name: node-_NODE_ID_-claim0
      restartPolicy: Always
      volumes:
      - name: node-_NODE_ID_-claim0
        persistentVolumeClaim:
          claimName: node-_NODE_ID_-claim0
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    atn.service: node-_NODE_ID_-claim0
  name: node-_NODE_ID_-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app: quorum-consortium
    version: '1'
  creationTimestamp: null
  labels:
    service: node-_NODE_ID_
  name: node-_NODE_ID_
spec:
  clusterIP: "_NODE_IP_"
  ports:
  - name: "8545"
    port: 8545
    targetPort: 8545
  - name: "23000"
    port: 23000
    targetPort: 23000
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    service: node-_NODE_ID_
status:
  loadBalancer: {}
---
