apiVersion: v1
kind: Service
metadata:
  annotations:
    app: consortiumchain
    version: '1'
  creationTimestamp: null
  labels:
    name: node-endpoint
  name: node-endpoint
spec:
  clusterIP: 10.23.250.0
  ports:
  - name: rpc
    port: 8545
    targetPort: 8545
  selector:
    app: consortiumchain
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    explorer.version: "1"
  creationTimestamp: null
  labels:
    name: explorer
  name: explorer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service.app: explorer
    spec:
      containers:
      - name: explorer-ui
        env:
        - name: REACT_APP_EXPLORER
          value: http://_EXPLORER_IP_:8081
        image: _EXPLORER_UI_IMAGE_
        ports:
        - containerPort: 5000
        resources: {}
      - name: explorer-backend
        env:
        - name: EXPLORER_PORT
          value: "8081"
        - name: JAVA_OPTS
        - name: MONGO_CLIENT_URI
          value: mongodb://localhost:27017
        - name: MONGO_DB_NAME
          value: consortium-explorer
        - name: NODE_ENDPOINT
          value: http://10.23.250.0:8545
        - name: UI_IP
          value: http://_EXPLORER_IP_:5000
        image: _EXPLORER_BACKEND_IMAGE_
        ports:
        - containerPort: 8081
        resources: {}
      - name: explorer-mongodb
        command:
        - mongod
        - --smallfiles
        - --logpath=/dev/null
        - --bind_ip
        - 0.0.0.0
        image: _EXPLORER_MONGO_IMAGE_
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    explorer.version: "1"
  creationTimestamp: null
  labels:
    service: explorer
  name: explorer
spec:
  type: LoadBalancer
  loadBalancerIP: 35.229.221.95
  ports:
  - name: ui
    port: 5000
    targetPort: 5000
  - name: backend
    port: 8081
    targetPort: 8081
  selector:
    service.app: explorer
status:
  loadBalancer: {}
