apiVersion: v1
kind: Service
metadata:
  annotations:
    app: quorum-consortium
    version: '1'
  creationTimestamp: null
  labels:
    app-name: quorum-consortium
  name: node-endpoint
spec:
  clusterIP: 10.100.23.226
  ports:
  - name: "8545"
    port: 8545
    targetPort: 8545
  selector:
    app: quorum-consortium
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    explorer.version: "1"
  creationTimestamp: null
  labels:
    service: explorer
  name: explorer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: explorer
    spec:
      containers:
      - name: explorer-ui
        env:
        - name: REACT_APP_EXPLORER
          value: http://192.168.99.100:32001
        image: blkio10/explorer-ui-free:1.0.0
        ports:
        - containerPort: 5000
        resources: {}
      - name: explorer-backend
        env:
        - name: EXPLORER_PORT
          value: "8081"
        - name: JAVA_OPTS
        - name: MONGO_CLIENT_URI
          value: mongodb://localhost:27017
        - name: MONGO_DB_NAME
          value: consortium-explorer
        - name: NODE_ENDPOINT
          value: http://10.100.23.226:8545
        - name: UI_IP
          value: http://192.168.99.100:32000
        image: blkio10/explorer-free:1.0.0
        ports:
        - containerPort: 8081
        resources: {}
      - name: explorer-mongodb
        command:
        - mongod
        - --smallfiles
        - --logpath=/dev/null
        - --bind_ip
        - 0.0.0.0
        image: mongo:3.4.10
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    explorer.version: "1"
  creationTimestamp: null
  labels:
    service: explorer
  name: explorer
spec:
  type: NodePort
  ports:
  - name: "5000"
    nodePort: 32000
    port: 5000
    targetPort: 5000
  - name: "8081"
    nodePort: 32001
    port: 8081
    targetPort: 8081
  selector:
    service: explorer
status:
  loadBalancer: {}
